utopian-io/utopian.io

src/styles/modules/feed-layout.less
src/styles/modules/post-layout.less
src/styles/modules/settings-layout.less
src/styles/modules/topnav-layout.less

I added padding for the main content areas (.layout-*) on small screens
and fixed a line break issue in firefox in the .right part of topnav when signed in.

Minor style fixes

---

src/components/Navigation/Topnav.less

The search input was 1px to small, which resulted in this double border.

fixed search input height

---

src/components/Comments/CommentForm.js
src/components/Comments/EmbeddedCommentForm.js
src/components/Editor/Editor.js

Wanted to give things a go with bringing over bug fixes from the Busy upstream. Not sure if you're open to these kind of PRs right now, so just let me know.
If you find this useful, I'll file it on Utopian and look at what other bug fixes / features can be brought over easily.
Editor: Place Cursor & Newline After Inserted Image (#912)
This fix ensures that, when inserting an image:
- the newline placed after the image is no longer placed at the end of the input
- the cursor is no longer placed at the end of the input

Editor: Place Cursor & Newline After Inserted Image

---

src/actions/projects.js

Previous end point https://api.github.com/search/repositories?${querystring.encode(q)} was encoding the +fork:true as well. If that is encode, github did not recognize it. So we need to encode only q part and add +fork:true&sort=stars&order=desc.

Able to search fork projects as well

---

src/components/Sidebar/SimilarPosts.js
src/components/Sidebar/SimilarPosts.less
src/post/Write/Write.js

By displaying similar contributions in the side bar, users will have an easier time avoiding duplicate contribution submissions. Thereby helping free up a moderator's time as well. The look up works exactly the same way that search does, including title and body, displaying the top results.
A `SimilarPosts` React component was created that carries the necessary functionality of handling the API call. It uses a `data` prop that contains the fields necessary to start the search. The same API endpoint as searching is used when invoking the API call. This ensures that the same results are received as you would from searching. The results are stored in a state and then displayed to the user.
Adjusting what data gets returned is easy to do within the created React component. An …

Display similar contributions to the user

---

LICENSE
README.md

After discussing licensing with Elear, I was asked to propose this update to the licensing for Utopian.io. As Utopian is an open source project but not a base resource, I'm proposing we move to a GPL license which will maintain opensource rights, but also allow Utopian to grow unhindered.
Under MIT licensing, users could fork Utopian and distribute the software closed-source, whereas, with GPL users would have to open their source before distributing the software.

Updated License

---

README.md

The `README.md` is the first thing Github users see when they view this repository, and if it's as dry and useless as it is right now, it doesn't seem inviting for others to contribute.
I've added:
* better descriptions
* screenshots
* information on running Utopian locally
* info on API Server
and more, to make sure everyone knows how to contribute to Utopian.

Strengthen README.md with Local Installation Directions, more information

---

src/components/Navigation/Topnav.less
src/styles/common.less

Fixes #95, #98 
Changes I made for #95:
- forced with `!important` the search combobox (`.ant-select-dropdown`) to have position fixed (like the top nav) so that it will not scroll with the rest of the content.
Changes I made for #98:
- set a lower `z-index` for `.ant-select-dropdown` so that the vote's tooltip will always be under the vote's modal

Fixes tooltip over modal and floating combobox issues

---

src/components/Navigation/Topnav.js
src/feed/SubFeed.js

- Closes #193: Dropdown menu not functioning properly
- Now when changing the search type it also filters the posts
- Only changes the path when on a valid path (home page or other filters)
- This will not change the path if you are currently writing a post or on any other invalid paths, it will only change the search type like normal

changing search type now filters posts also

---

README.md
package.json

Quote from readme
> If you change a `.js` file, the `webpack` will probably _automatically_ update itself
This change fixed the **probably** part for me. Can you check if it becomes consistent after this change and if so merge it?

Fixed webpack 'probably' recompiling on change

---

webpack/makeConfig.js
webpack/webpack-dev-server.js
webpack/webpack.server.config.js

So editing a *.less file will now auto compile properly.
Note that dot (.) wasn't escaped via backslash in old version. That was the problem.

Fixed regex pattern in webpack configs not matching *.less files

---

src/components/Sidebar/GithubConnection.less

Hi there !
I've just discovered the Utopian project & found it really cool. 
Saw a small bugs when repository has a long name you can find the fix in this PR
Before : 
After : 
Do you want me to squash those commit into one ?

Ellipsis on project list

---

src/Wrapper.js

This PR fixes the issue with the GitHub token. When the GitHub token expires, the frontend freezes because it depends on the `repos` endpoint that doesn't return anything.
To fix it, I changed the frontend to load the page, even if the user's repos are not loaded yet.

Fix bug when loading GitHub repos

---

src/components/Navigation/Topnav.js
src/components/Story/Story.js

- Fixes #211: Inclusion of the `%` symbol in the search bar causes errors
- Removed `@, #, %, and *` from any search queries
- Slightly cleaned up unused code
Demonstration below, look at the url to see `utopian.io` vs. `localhost`

Fix invalid uri characters

---

src/Wrapper.js
src/app/appActions.js
src/app/appReducer.js
src/comments/Comments.js
src/components/CommentFooter/CommentFooter.js
src/components/Comments/Comment.js
src/components/Comments/Comments.js
src/components/Story/StoryFull.js
src/components/StoryFooter/StoryFooter.js
src/helpers/user.js
src/post/PostContent.js
src/reducers.js
src/vendor/steemitHelpers.js

Voting slider in utopian.io was inaccurate. SBD price spike broke the mechanism completely. The formula had to be updated by current_median_history_price factor.
Old:
Fixed:
True values:

 Fix of estimated upvote amount bug

---

src/helpers/user.js

Issue: every user's visible rank is "Plankton". It didn't change depending on Vests amount. The problem was incorrect number parsing from string text ("XXX VESTS")

Fix user rank on the profile page

---

src/components/Rules.js

*Some explanation for the changes:*
**Your Utopian account must be connected to your GitHub account.
The repository on GitHub must accept <a href="https://help.github.com/articles/about-issues/">issues</a>.**
This makes sure an issue on GitHub is filed and the project maintainer has a chance to actually see the bug and react.
**<b>Bug Reports</b> for projects in <a href="https://en.wikipedia.org/wiki/Software_release_life_cycle">pre-alpha stage</a> will not be accepted.**
To avoid being flooded with bugs, we need to draw a clear line. Projects that are in very early stage (preview/pre-alpha) obviously contain a lot of bugs and the developers probably know about them or at least the about fact that there are bugs. I think this Wikipedia article gives us a clear definition.
**Cosmetic …

updated bug-hunting rules

---

src/components/Rules.js

*Some explanation for the changes:*
This addresses the fact that there are different types of contributions that need to be handled differently, which is reflected in the other rules.
Contributors get rewarded for their work and therefore this work has to be evaluated by the moderators first. This is simply not possible if contributors don't use Git in it's intended way and make commits, that crash the browser when viewed on GitHub.
Software should always be activley maintained and up to date because hopefully there are users who are actually using it and relying on it.
No work. No reward. Makes sense I guess. We had contributions that only contained an updated dependencies file or unified code formatting.
Utopian can reward one super awesome innovative calculator app and maybe two or …

updated development rules

---

package.json
src/components/Editor/Editor.js
src/components/Editor/EditorTask.js
src/components/Editor/EditorToolbar.js
src/components/Story/Body.js
src/components/Story/Body.less
src/vendor/SanitizeConfig.js

I am using Utopian.io for quite a time now and realised using code blocks is buggy. Also code blocks do not use code highlighting and a toolbox button is missing. So I added it.
Currently when adding blank new lines inside a code block, the formatting after it is completely wrong and inside the code block
Example:
I fixed it:
When working with code examples it is always great to have a simple code highlighting, so the end-user can read the code more easily.
It works for the most basic programming languages and is supported by default from remarkable. To highlight the code correctly a new node package is used in combination with remarkable, named 'highlight.js' 
Hotkey and Button both works, they insert a code block at the cursor position.
Overall some simple changes, to make have a better …

Feature/Add Code Block Highlighting + Code Block Bug Fix + Code Block Toolbar Button

---

src/components/Navigation/Sidenav.js
src/statics/CookiePolicyBanner.js
src/statics/CookiePolicyBanner.less

Hotfixes for commit #326:
- Better RWD support - now banner do not take too much space on mobile, screens:
- Hotfix: there was an issue in sidenav - I did a mistake, and didn't change aname for route in sidenav
- made links more readable: the links in my not calibrated screen looked good, but in reality the contrast was too low. Now links are white.

Cookie policy hotfix & RWD

---

src/components/Rules.js

there is a role named "translator" which can proofread his/her words, but can't assign new proofreaders/translator
so instead of asking for "proofreader" permission, we should ask for "translator" permission.

[RULES] urgent translations rule change (draft)

---

src/components/Navigation/Topnav.js

Fix typo in React's `onClick` that was breaking the contribute button on the front page.
Confirmed working locally.
#220 #397

Fix contribution button on front page #220

---

src/sc2.js
webpack/webpack-dev-server.js

`UTOPIAN_APP` defaults to `'utopian.app'`
use `export UTOPIAN_APP=utopian-test` to switch to `'utopian-test'` or something else
(it's just annoying to change code for that....)

use env var to switch between from utopian.app to utopian-test

---

src/auth/RequireTos.js

The button "Scroll Down" can be clicked all the time and opens a popup
"Scroll down to accept". Should be renamed to "Accept", disabled until
scrolled down and all cancel actions should lead to logout.
After accepting, the popup still appears for a not so short moment when
loading a pege.
For: https://github.com/utopian-io/utopian.io/issues/411

Change ScrollDown to Accept, & Logout on cancel

---

src/components/Story/InlineCategoryEdit.js
src/components/Story/InlineRepoEdit.js
src/components/Story/InlineTagEdit.js

* `src/components/Story/InlineCategoryEdit.js` 
* `src/components/Story/InlineRepoEdit.js`
* `src/components/Story/InlineTagEdit.js`
* added setting of values to `state` when changing contributions; this was done mainly by setting incoming properties in `componentWillReceiveProps()` and set them to state
* added setting of initial value in `componentWillMount()`

Hotfix inline category, repo, and tags not properly set

---

src/actions/pullRequests.js

increases number of returned results (for the repository dropdown) from 30 to 100.
hotfixes this one: https://utopian.io/utopian-io/@mkt/can-t-select-my-pull-requests-if-there-are-to-many-new-ones
why there are linked PRs in a bug hunting contribution you ask?... well, this seems to be another bug. :D

added per_page parameter to GitHub PR api call

---

src/components/Rules.js
src/components/RulesTask.js
src/statics/Rules.js
src/statics/Rules.less

I think this *"Utopian moderators / supervisors have the full right to reject or accept submissions and to assess its quality, even if the submission meets all the rules."* should go to the top.
Also fixed those spacings that were tighter than your girlfriend...
...and enclosed all guideline-rules in \<i>\</i>
before:
after:
WOW!

moved important rule to top and improved style/spacings

---

common/constants/cryptos.js

Hello Utopian Team,
With the CryptoCompare API change, the SBD endpoint has been changed to SBD *
This is why the SBD value on the Wallet page is not displayed or displayed incorrectly.

Fix SBD rate
