src/components/Button/Github.less

I know I'm pedantic but...
this looks better...

added button padding

---

src/components/Navigation/Topnav.js
src/components/Navigation/Topnav.less

removed border from contribution button on hover

---

src/components/Button/Github.js

- src/components/Button/Github.js: remove scope to reduce permissions required to sync with github (closes #77)

lower github permissions

---

src/styles/modules/topnav-layout.less

the logo of navigation bar has look on the buttom .
i've change `vertical-align from` : **middle** to  **text-top** for a better apparence .

Update Top-Nav Brand CSS

---

src/feed/SubFeed.js
src/user/UserFeed.js

This commit allows blog posts such as my own to show up in User Profiles such as https://utopian.io/@mooncryption.

Blog Posts Show Up in User Profile

---

src/components/Editor/EditorAnnouncement.js
src/components/Story/Contribution.js
src/components/Story/Story.js
src/components/Story/StoryFull.js
src/feed/SubFeed.js

If `@x` submits a contribution and it hasn't been approved yet *and* it also hasn't been flagged yet, it will be shown in the user feed. This is by request of @diegopucci.

Show Unmoderated Posts in User Profile Feed

---

src/components/Story/Blog.js
src/components/Story/Blog.less
src/components/Story/Contribution.js
src/components/Story/Story.js
src/components/Story/StoryFull.js

* New in-progress icons (`type="safety"`) for posts/blogs
* These icons now show up on blogs too 🤣

In-Progress Icons for Posts And Blogs

---

src/components/Navigation/Sidenav.js
src/components/Navigation/Sidenav.less
src/components/Navigation/Topnav.js
src/feed/Feed.js
src/feed/SearchFeed.js
src/feed/SubFeed.js

This commit adds a new task requests panel. Pretty hard work but I was able to do it 😄 
The panel is accessible from the left-side navigation. Task Requests are restricted there.

Add Task Requests Panel!

---

src/statics/EmptyFeed.js

A new `EmptyFeed` for Tasks, and fixed grammar mistakes.

New Empty Feed View for Tasks, Fixed Grammar Errors

---

src/routes.js
src/statics/Rules.js
src/statics/WelcomeModerator.js
src/statics/WelcomeModerator.less

https://utopian.io/welcome-moderator will become a new 'guideline' ruleset for moderators, based on this pull request!
This should help new moderators who join.

Welcome Moderator - New Moderation Guide

---

src/statics/EmptyFeed.js
src/statics/Rules.js
src/statics/WelcomeModerator.js
src/statics/WelcomeModerator.less

LESS Changes to the Welcome Moderator Page

Welcome Moderator - LESS Changes

---

src/feed/SearchFeed.js
src/feed/SubFeed.js

Reverts utopian-io/utopian.io#105
The issue isn't fixed just yet

Revert "Fixing Issue #96 and Search Issue when Scrolling"

---

src/components/Navigation/Topnav.less
src/styles/modules/topnav-layout.less

Old changement Cause effect for the brand on mobile view .
So i correct it by this changement .
- delete old changement for navigation brand in ;
**src/styles/modules/topnav-layout.less**
- update navigation brand css in ;
**src/components/Navigation/Topnav.less**

Correct old changement for Navigation brand

---

src/locales/ca.json

translate string like_slider_info for Catalan.

Update ca.json like_slider_info

---

src/components/Rules.js
src/components/Sidebar/SideAnnouncement.js
src/components/Sidebar/SideAnnouncement.less

Edited Rules:
* Translations now have more specific rules
* Copywriting now doesn't require pull requests anymore

Fixed Announcements, Edited Rules

---

src/actions/projects.js

Edited Access Token

---

src/actions/projects.js
src/app/Sidebar/RightSidebar.js
src/components/Sidebar/GithubConnection.js
src/components/Sidebar/GithubConnection.less
src/post/Write/Write.js
src/post/Write/WriteAnnouncement.js
src/post/Write/WriteBlog.js
src/user/GithubConnect.js

Moved Organization Projects to API's End (back-end) #138

Move Organization Projects to API End

---

src/actions/constants.js
src/actions/user.js
src/app/Sidebar/UserInfo.js
src/components/BanUser.js
src/components/BanUser.less
src/components/Button/Action.js
src/components/Button/Action.less
src/components/Story/StoryFull.js
src/components/Story/StoryFull.less
src/components/UserHeader.js
src/post/Write/Write.js
src/post/Write/WriteAnnouncement.js
src/post/Write/WriteBlog.js
src/user/GithubConnect.js

- This commit allows you to ban users on profile pages like https://utopian.io/@mooncryption, but don't ban me! :) 
- The actual banning mechanism is pretty weak and can be circumvented, so that's a todo

Allow for Banned Users

---

src/components/Editor/EditorAnnouncement.js

Changed the title name from "Contribution title" to "Task request title"

Correct title name

---

src/styles/modules/popover-layout.less

This is a fix and it work. Maybe this is not correct flux to improve utopian.

fix #143 Dropdown menu is not scrolling properly on big tablet/Dekstop

---

src/components/Navigation/Topnav.js
src/components/Story/Story.js

- Fixes #178: Edit Button Just Spins and Does Not Load Edit Page in Utopian.io
- Passes through the onEditClick prop which must have been missed
Before:
After:

Fixed Edit Button on User Profile

---

src/components/Navigation/sidenav2

the old sidebar navigator look like this 
https://res.cloudinary.com/hpiynhbhq/image/upload/v1513117510/avibhoyaoyobaeho7pd3.png
The new sidebar navigator will look like https://res.cloudinary.com/hpiynhbhq/image/upload/v1513116997/tkoqcoyioil1ewkurtdx.png

Add Rules & Faq to Utopian.io Sidenav

---

src/components/Navigation/Topnav.less

This is for issue #234 I did not have a chance to test it, but I think it will work.

fixed chat notification settings checkboxes

---

src/components/Story/StoryFull.js

current channel bring us to collaborators channel on discord.
So it need to fix with correct help channel.

fix incorrect discord help channel for the comment template.

---

src/components/Rules.js

Update Rules.js (Graphics)

---

src/components/Rules.js
src/statics/Rules.js

Blog posts are quite difficult to moderate with the other languages and it doesn't really bring anything valuable to have them in other languages at the moment.

Update Rules.js (Blogs language)

---

src/components/Rules.js

**If you create a GitHub repository with additional material (like code samples), make sure to choose the repository of the project your tutorial is about and not your own repository. You can provide links to your repository in your post.**

added (video-)tutorial rule

---

src/components/Rules.js

added
**basic programming concepts (variables, operators, loops, etc.)**
to
**Design or video editing related tutorials, gameplay, simple on-screen instructions and ubiquitous functions (Save, Open, Print, etc.) will not be accepted.**
changed
**Video Tutorials must be unique. If a similar, publicly available tutorial already provides the same or a better learning experience, your tutorial will not be accepted.**
to
**Your contribution can be rejected if the moderator provides a link to another tutorial that covers the same topic better.**

updated (video-)tutorials again

---

src/statics/Rules.js

fixes https://github.com/utopian-io/utopian.io/issues/310

[RULES] replaced discord with new application form

---

src/statics/Rules.js

fixes https://github.com/utopian-io/utopian.io/issues/314

changed moderation issue section

---

src/Wrapper.js
src/components/Navigation/Sidenav.js
src/routes.js
src/statics/CookiePolicy.js
src/statics/CookiePolicyBanner.js
src/statics/CookiePolicyBanner.less
src/statics/Rules.js

Resolving issue #321: https://github.com/utopian-io/utopian.io/issues/321
Couldn't find a cookie icon in antd framework, so used a flag icon instead. Also I didn't know how to test cross-subdomain implementation of saved cookie... According to [the documentation](https://github.com/js-cookie/js-cookie) it should work on every subdomain, but it's defenetly something to verify. On localhost works correctly. 
Screenshots:

#321 Cookie policy feature

---

src/components/Rules.js

Fixes: https://github.com/utopian-io/utopian.io/issues/317

added new translation rule for crowdin

---

src/components/Navigation/Sidenav.js

Fix two FAQ link in sidenav

---

src/components/Rules.js

Hi, Dev team I corrected some line to be more clear and not confusing.

Hi, Dev team I corrected some line.

---

src/components/UserMenu.js
src/styles/modules/feed-layout.less

- CSS bug on date filter
- isModerator() function on UserMenu

Fixes on moderation feed

---

src/Wrapper.js
src/components/Navigation/Sidenav.js
src/routes.js
src/statics/CookiePolicy.js
src/statics/CookiePolicyBanner.js
src/statics/CookiePolicyBanner.less
src/statics/Rules.js

According to @wehmoen's problems with synchronization between develop and master branch (the #328 & #350 features were set to critical priority and staged directly into master, skipping develop) I was forced to manually merge changes from the PR and paste it into develop branch. This PR is the same as #328 and #350 combined.

Manual merge Cookie Policy PR into develop branch

---

src/routes.js

Bug fix
Static pages were missing

add missing references to privacy policy

---

package-lock.json

after running `npm i` the lock file was changed.... guess this needs to be committed.

updated dependencies in lockfile

---

src/components/Story/StoryFull.js

disable click on background closes verify modal

---

src/components/CommentFooter/CommentFooter.js

if you are not logged in and try to upvote a comment, the signin/up modal will show, like for the main post
extends https://github.com/utopian-io/utopian.io/pull/365

added signin/up modal to comments

---

.gitignore
src/components/Navigation/Topnav.js
src/feed/SubFeed.js

Solves most of the problems listen on: 
https://github.com/utopian-io/utopian.io/issues/411

Fix Feed with tab selection & Review feed

---

src/feed/SubFeed.js

Solves:
https://github.com/utopian-io/utopian.io/issues/423
https://github.com/utopian-io/utopian.io/issues/427

fix user contribution endless skip loop

---

src/components/Story/Contribution.js

Solves: 
https://github.com/utopian-io/utopian.io/issues/430

add graphics category

---

src/components/UserMenu.js

add a methjod to verify the state.current property in UserMenu.js and render the appropriate element with the correct data-key

UT424-keeping-contributions-menu-entry-active

---

src/components/Navigation/Sidenav.js
src/components/Navigation/Sidenav.less

menu when logged out

---

src/auth/RequireTos.js

Scrolling height seems to be a bit off on different browsers. This pr tries to fix this issue.

update height checks

---

src/components/Story/StoryFull.js

(...that it currently has no effect on the reward)

added note to quality slider

---

src/statics/CookiePolicyBanner.js
src/statics/CookiePolicyBanner.less

cookie notice style

---

src/components/Rules.js
src/components/RulesTask.js
src/statics/Rules.js

"Forgot"... to add Info about moderator/supervisor applications. I think we should handle this differently. This also does not really belong into the rules. We can create a separate page for that, once we start to onboard new mods again.

rules update 11

---

src/components/Rules.js

require direct permission from project owner

updated visibility/translation rules
